[package]
name = "file_dedupe"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.87"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5.6"

